---
title: "Champion Series Squads"
output:
  html_document: 
    includes:
      in_header: analytics.html
  pdf_document: default
  word_document: default
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.width=10, fig.height=6, fig.path='Figs/',
                      echo=FALSE, warning=FALSE, message=FALSE)

# Show a maximum of 100   
options(tibble.print_max = 100, tibble.print_min = 15)

library(gt)
library(tidyverse)
library(utf8)
library(DT)

loc = locale(date_names = "en", date_format = "%AD", time_format = "%AT",
  decimal_mark = ".", grouping_mark = ",", tz = "UTC",
  encoding = "UTF-8", asciify = FALSE)

path = "C:/project/fortnite/r/champion-series-squads/data/"

```
Back to [Fortnite Ping](<https://www.fortniteping.com>) 

***Last updated October 28, 2019***


# Regions {.tabset .tabset-fade}

## Europe
```{r europe_table}

region <- read_csv(str_c(path,"Europe.csv"))
datatable(region)
```

## NA East
```{r na_east_table}
region <- read_csv(str_c(path,"NA East.csv"))
datatable(region)
```

## NA West
```{r na_west_table}
region <- read_csv(str_c(path,"NA West.csv"))
datatable(region)
```

## Brazil
```{r na_brazil_table}
region <- read_csv(str_c(path,"Brazil.csv"))
datatable(region)
```

## Asia
```{r na_asia_table}
region <- read_csv(str_c(path,"Asia.csv"))
datatable(region)
```

## Oceania
```{r oceania_table}
region <- read_csv(str_c(path,"Oceania.csv"))
datatable(region)
```

## Middle East
```{r middle_east_table}
region <- read_csv(str_c(path,"Middle East.csv"))
datatable(region)
```