function playerChart(a){function b(){var a=0;t.forEach(function(){var f=a,b=t[f].name,g=0===f?"1.8em":"1.3em",d=0===f?t[f].x:240+h.gap+h.width*(f-1)+t[f].x;"Earned Quals"===b?(e.append("text").attr("x",d+12).attr("y",34).text("Earned").attr("font-family","burbank").attr("font-size","1.2em").attr("fill","black").attr("pointer-events","none"),e.append("text").attr("x",d+16).attr("y",58).text("Quals").attr("font-family","burbank").attr("font-size","1.2em").attr("fill","black").attr("pointer-events",
"none")):"Elims"===b?(e.append("text").attr("x",d+8).attr("y",34).text("Elim").attr("font-family","burbank").attr("font-size","1.2em").attr("fill","black").attr("pointer-events","none"),e.append("text").attr("x",d).attr("y",58).text("Points").attr("font-family","burbank").attr("font-size","1.2em").attr("fill","black").attr("pointer-events","none")):"Elim %"===b?(e.append("text").attr("x",d+5).attr("y",35).text("Elim").attr("font-family","burbank").attr("font-size","1.2em").attr("fill","black").attr("pointer-events",
"none"),e.append("text").attr("x",d+10).attr("y",62).text("%").attr("font-family","burbank").attr("font-size","1.5em").attr("fill","black").attr("pointer-events","none")):"Placement"===b?(e.append("text").attr("x",d+5).attr("y",34).text("Placement").attr("font-family","burbank").attr("font-size","1.0em").attr("fill","black").attr("pointer-events","none"),e.append("text").attr("x",d+15).attr("y",55).text("Points").attr("font-family","burbank").attr("font-size","1.0em").attr("fill","black").attr("pointer-events",
"none")):"Placement %"===b?(e.append("text").attr("x",d+5).attr("y",34).text("Placement").attr("font-family","burbank").attr("font-size","1.0em").attr("fill","black").attr("pointer-events","none"),e.append("text").attr("x",d+25).attr("y",62).text("%").attr("font-family","burbank").attr("font-size","1.5em").attr("fill","black").attr("pointer-events","none")):(f=0===f?58:46,g=e.append("text").attr("x",d).attr("y",f).text(b).attr("font-family","burbank").attr("font-size",g).attr("fill","black").attr("pointer-events",
"none"),"Rank"===b&&(y=g));a++});l&&l.attr("stroke-width",filters.week&&"rank"===filters.sort?9:0)}function c(){var a=h.height/2;x=e.append("polygon").attr("points","180,"+(a-2)+" 230,"+(a-2)+" 205,4").style("fill","darkgrey").attr("pointer-events","bounding-box").attr("stroke","black").attr("stroke-width",0).on("mouseover",function(a){d3.select(this).attr("stroke-width",5)}).on("mouseout",function(a){d3.select(this).attr("stroke-width",0)}).on("click",function(a){u("up")});z=e.append("polygon").attr("points",
"180,"+(a+5)+" 230,"+(a+5)+" 205,"+2*a).style("fill","darkgrey").attr("pointer-events","bounding-box").attr("stroke","black").attr("stroke-width",0).on("mouseover",function(a){d3.select(this).attr("stroke-width",5)}).on("mouseout",function(a){d3.select(this).attr("stroke-width",0)}).on("click",function(a){u("down")})}function u(a){"down"===a&&(filters.page+=1);"up"===a&&--filters.page;r()}function q(a,b){if(!a)throw"You must sort by something";d3.selectAll("svg").selectAll("rect").each(function(f){f&&
f.code===a&&d3.select(this).transition().duration(100).attr("stroke-width",b)})}function m(a){if(null===a)filters.player="",null!=v&&(v.attr("stroke",0),v=null),showPlayerOnWeekChart("");else{a=d3.select(a);var b=A[a.attr("data")].key;""===filters.player?(filters.player=b,a.attr("stroke-width",9),showPlayerOnWeekChart(b),v=a):(""!=filters.player?(v.attr("stroke-width",0),v=a,filters.player=b,a.attr("stroke-width",9)):(a.attr("stroke-width",9),filters.player="",v=null),showPlayerOnWeekChart(b))}}function w(){var a=
filters.sort,b="rank"!==filters.sort?d3.descending:d3.ascending,d=d3.nest().key(function(a){return a.key}).sortKeys(b).entries(n.dimension().top(Infinity));d.sort(function(d,f){return b(d.values[0].value[a],f.values[0].value[a])});g=function(a,b){var d=b.map(function(a){return a.player}).reduce(function(a,b){a[b]=1;return a},{});return a.filter(function(a){a.color=playerColors[a.key];return 1===d[a.key]})}(d,playerDim.top(Infinity));g.sort(function(d,f){return b(d.values[0].value[a],f.values[0].value[a])});
filters.playerCount=g.length}function r(){function a(a,b,f){if(0==b)return a.key;a=a.values[0].value[t[b].code];return 1!=b?t[b].format(a):""===filters.week?d+f+1:a}var d=20*filters.page,k=20*(filters.page+1),v=g.slice(d,k);A=[];for(var B=0;20>B;B++)A.push(v[B]);e.selectAll("text").remove();b();var c=0;A.forEach(function(b){1===v.length&&0==c&&e.select(".row0").each(function(a){m(this)});if(b){e.selectAll(".row").data(t).enter().append("text").attr("x",function(d,f){if(0===f)return 68;var e=10*(6-
a(b,f,c).toString().length);1===f&&(e-=18);return 240+e+h.gap+10+h.width*(f-1)}).attr("y",p+34*c+20).text(function(f,d){return a(b,d,c)}).attr("fill","black").attr("font-size","1.3em").attr("pointer-events","none").attr("font-weight",function(a){return a.code===filters.sort?1E3:400});var d=e.select(".row"+c),f=E[b.color];filters.region&&("NA East"===filters.region&&(f="#319236"),"NA West"===filters.region&&(f="#9D4DBB"),"Europe"===filters.region&&(f="#4C51F7"),"Oceana"===filters.region&&(f="#DB4441"),
"Brazil"===filters.region&&(f="#3E93BC"),"Asia"===filters.region&&(f="#8B4513"));d.transition().attr("fill",f);e.select(".s"+c).transition().style("fill-opacity",-1!=soloQualifications.indexOf(b.key)?1:0);e.select(".d"+c).transition().style("fill-opacity",-1!=duoQualifications.indexOf(b.key)?1:0)}else e.select(".row"+c).attr("fill","none").attr("stroke-width",0),e.select(".s"+c).style("fill-opacity",0),e.select(".d"+c).style("fill-opacity",0);c++});""===filters.week?(y.text("#").attr("x",240+h.gap+
t[1].x+12).attr("y",59).attr("font-size","2.6em"),l.attr("fill","none").attr("pointer-events","none").attr("stroke-width",0)):(y.text("Rank"),l.attr("fill","lightblue").attr("pointer-events","auto"));C(20,d,k);updateCounts()}function C(a,b,d){function f(a,b){a.style("fill-opacity",b?1:0);a.attr("pointer-events",b?"auto":"none")}g.length<a&&(f(x,!1),f(z,!1));0===filters.page&&f(x,!1);0<filters.page&&f(x,!0);d<g.length&&f(z,!0);d>=g.length&&f(z,!1)}var k=function(a){return a},F=d3.format(","),D=d3.format(",.1%"),
t=[{name:"Player",code:"player",x:8,format:k},{name:"Rank",code:"rank",x:16,format:k},{name:"Payout",code:"payout",x:9,format:F},{name:"Points",code:"points",x:13,format:k},{name:"Wins",code:"wins",x:17,format:k},{name:"Earned Quals",code:"earnedQualifications",x:0,format:k},{name:"Elims",code:"elims",x:15,format:k},{name:"Elim %",code:"elimPercentage",x:16,format:D},{name:"Placement",code:"placementPoints",x:0,format:k},{name:"Placement %",code:"placementPercentage",x:0,format:D}],E={green:"#319236",
purple:"#9D4DBB",blue:"#4C51F7",red:"#DB4441",teal:"#3E93BC",lime:"#3CFF3E",grey:"#B3B3B3",brown:"#8B4513"},h={left:150,top:0,height:69,width:80,gap:5};PlayerTableWidth=240+h.width*(t.length-1);var n=dc.baseMixin({}),p=h.height+14,l,y,x,z,d=PlayerTableWidth,v,A=[],g;n._mandatoryAttributes(["dimension"]);a=d3.select(a);var B,G=[];for(k=0;20>k;k++)G.push({num:k});var e=a.append("svg").attr("width",d).attr("height",1E3);(function(){e.selectAll("rect").data(t).enter().append("rect").attr("x",function(a,
b){return 0==b?0:240+h.gap+h.width*(b-1)}).attr("y",h.top+4).attr("width",function(a,b){return 0==b?240:h.width-h.gap-3}).attr("height",h.height).attr("fill",function(a,b){return 0==b?"none":"lightblue"}).attr("stroke","black").attr("stroke-width",0).attr("data",function(a){return a}).attr("rx",cornerRadius).attr("ry",cornerRadius).on("mouseover",function(a){a.code!==filters.sort&&d3.select(this).transition().duration(100).attr("stroke-width",3)}).on("mouseout",function(a){a.code!==filters.sort&&
d3.select(this).transition().duration(100).attr("stroke-width",0)}).on("click",function(a){if(a.code!==filters.sort){q(filters.sort,0);filters.sort=a.code;d3.select(this).transition().duration(100).attr("stroke-width",0);""!=filters.player?clearPlayer(null):(updateCounts(),filters.page=0,w(),r());a=this.x.baseVal.value;var b=this.y.baseVal.value;console.log(this);B.transition().duration(350).attr("x",a).attr("y",b)}}).each(function(a,b){1===b&&(l=d3.select(this))});b();c();q("payout",9);B=e.append("rect").attr("x",
240+h.gap+h.width).attr("y",h.top+4).attr("width",h.width-h.gap-3).attr("height",h.height).attr("fill","none").attr("stroke","black").attr("stroke-width",9).attr("pointer-events","none").attr("rx",cornerRadius).attr("ry",cornerRadius)})(e);(function(){G.forEach(function(a){e.append("rect").attr("data",a.num).attr("x",0).attr("y",p+34*a.num).attr("width",d).attr("height",28).attr("fill","none").attr("class","row"+a.num).attr("visible","hidden").attr("stroke","black").attr("stroke-width",0).on("mouseover",
function(a){a=d3.select(this);var b=A[a.attr("data")].key;filters.player!==b&&a.attr("stroke-width","4")}).on("mouseout",function(a){a=d3.select(this);var b=A[a.attr("data")].key;filters.player!==b&&a.attr("stroke-width","0")}).on("click",function(a){m(this)});e.append("circle").attr("cx",16).attr("cy",p+34*a.num+14).attr("r",10).attr("fill","gold").attr("fill-opacity",0).classed("s"+a.num,!0);var b=e.append("g").style("fill-opacity",0).attr("pointer-events","none").classed("d"+a.num,!0);b.append("circle").attr("cx",
39).attr("cy",p+34*a.num+11).attr("r",7).attr("fill","gold");b.append("circle").attr("cx",50).attr("cy",p+34*a.num+18).attr("r",7).attr("fill","gold")})})(e);n._doRender=function(){filters.page=0;w();r();return n};n._doRedraw=function(){return n._doRender()};clearPlayer=m;return n};function regionChart(a){function b(a){a?(q=!1,r.transition().duration(400).attr("stroke-width",0)):(a=c.find(function(a){return a.filter===filters.region}),q?r.transition().duration(250).attr("cx",a.x).attr("cy",a.y):(q=!0,r.attr("cx",a.x).attr("cy",a.y),r.transition().duration(100).attr("stroke-width",11)))}var c=[{x:50,y:80,color:"#319236",name:"NA EAST",filter:"NA East",textOffset:33},{x:150,y:80,color:"#9D4DBB",name:"NA WEST",filter:"NA West",textOffset:35},{x:250,y:80,color:"#4C51F7",name:"EUROPE",
filter:"Europe",textOffset:30},{x:50,y:180,color:"#DB4441",name:"OCEANA",filter:"Oceana",textOffset:32},{x:150,y:180,color:"#3E93BC",name:"BRAZIL",filter:"Brazil",textOffset:26},{x:250,y:180,color:"#8B4513",name:"ASIA",filter:"Asia",textOffset:19}],u=[];a=d3.select(a);var q=!1,m=dc.baseMixin({}),w=a.append("svg").attr("width",300).attr("height",430);w.append("text").attr("x",10).attr("y",20).text("Regions").attr("font-size","1.6em").attr("fill","black");c.forEach(function(a){var b=w.append("circle").attr("cx",
a.x).attr("cy",a.y).attr("r",45).attr("fill",a.color).attr("stroke","black").attr("stroke-width",0).attr("data",a.filter).on("mouseover",function(a){d3.select(this).attr("data")!==filters.region&&d3.select(this).transition().duration(100).attr("stroke-width",4)}).on("mouseout",function(a){a=d3.select(this);a.attr("data")!=filters.region&&a.transition().duration(100).attr("stroke-width",0)}).on("click",function(a){C(d3.select(this))});u.push(b);w.append("text").attr("x",a.x-a.textOffset).attr("y",
a.y+6).text(a.name).attr("font-size","1.4em").attr("fill","black").attr("pointer-events","none")});var r=w.append("circle").attr("cx",50).attr("cy",80).attr("r",45).attr("fill","none").attr("stroke","black").attr("stroke-width",0).attr("pointer-events","none");var C=function(a){var c=a.attr("data");clearPlayer(null);if(""===filters.region)filters.region=c,m.filter(filters.region),a.transition().duration(100).attr("stroke-width",11),m.redrawGroup(),updateCounts(),b(!1);else if(filters.region!=c){var k=
filters.region;u.forEach(function(a){a=d3.select(a._groups[0][0]);a.attr("data")==k&&(m.filter(k),a.transition().duration(100).attr("stroke-width",0))});filters.region=c;m.filter(filters.region);a.transition().duration(100).attr("stroke-width",0);m.redrawGroup();updateCounts();b(!1)}else filters.region="",m.filter(null),a.transition().duration(100).attr("stroke-width",0),m.redrawGroup(),updateCounts(),b(!0)};return m};function weekChart(a){function b(a){if(a)h=!1,x.transition().duration(400).attr("stroke-width",0);else{q.find(function(a){return a.name===filters.week});a=n._groups[0][0].x.baseVal.value;var b=n._groups[0][0].y.baseVal.value;h?x.transition().duration(300).attr("x",a).attr("y",b):(h=!0,x.attr("x",a).attr("y",b),x.transition().duration(100).attr("stroke-width",11))}}function c(a,b,c,g){return a.append("text").attr("x",b+g.x).attr("y",c+g.y).text("Wins").attr("font-size",g.size).attr("fill","black").attr("pointer-events",
"none").attr("fill-opacity","0.0")}function u(a,b,c,g){a=a.append("g").style("fill-opacity",0).attr("pointer-events","none");1==g%2?a.append("circle").attr("data",g).attr("cx",28).attr("cy",22).attr("r",10).attr("fill","gold").attr("transform","translate("+(b-13)+","+(c-7)+")"):(a.append("circle").attr("data",g).attr("cx",26).attr("cy",20).attr("r",7).attr("fill","gold").attr("transform","translate("+(b-13)+","+(c-7)+")"),a.append("circle").attr("data",g).attr("cx",36).attr("cy",30).attr("r",7).attr("fill",
"gold").attr("transform","translate("+(b-13)+","+(c-9)+")"));return a}var q=[{num:1,name:"Week 1",type:"Solo",done:!0},{num:2,name:"Week 2",type:"Duo",done:!0},{num:3,name:"Week 3",type:"Solo",done:!0},{num:4,name:"Week 4",type:"Duo",done:!0},{num:5,name:"Week 5",type:"Solo",done:!0},{num:6,name:"Week 6",type:"Duo",done:!0},{num:7,name:"Week 7",type:"Solo",done:!0},{num:8,name:"Week 8",type:"Duo",done:!0},{num:9,name:"Week 9",type:"Solo",done:!0},{num:10,name:"Week 10",type:"Duo",done:!1}],m=[],w=
[],r={x:25,y:54,size:"2em"},C={x:40,y:25,size:"1.2em"},k={x:8,y:45,size:"1.0em"},F={x:8,y:62,size:".9em"},D={x:8,y:79,size:".9em"},t={x:72,y:45,size:".9em"},E={x:72,y:62,size:".9em"};a=d3.select(a);var h=!1,n,p=dc.baseMixin({}),l=a.append("svg").attr("width",300).attr("height",515);l.append("text").attr("x",60).attr("y",25).text("Solo").attr("font-size","1.6em").attr("fill","black");l.append("text").attr("x",200).attr("y",25).text("Duo").attr("font-size","1.8em").attr("fill","black");var y=0;q.forEach(function(a){var b=
{},d="Solo"===a.type?10:155,g=97*Math.round((y-1)/2)+40,h="Duo"===a.type?"#9ACD32":"Red";a.done||(h="#B3B3B3");h=l.append("rect").attr("data",a.num).attr("x",d).attr("y",g).attr("width",135).attr("height",87).attr("fill",h).attr("stroke","black").attr("stroke-width",0).attr("rx",cornerRadius).attr("ry",cornerRadius).on("mouseover",function(a){var b=d3.select(this).attr("data");"Week "+b!==filters.week&&q.filter(function(a){return a.num==b})[0].done&&d3.select(this).transition().duration(100).attr("stroke-width",
4)}).on("mouseout",function(a){a=d3.select(this);"Week "+a.attr("data")!=filters.week&&a.transition().duration(100).attr("stroke-width",0)}).on("click",function(a){z(d3.select(this))});b.rect=h;w.push(u(l,d,g,a.num));a=l.append("text").attr("x",d+r.x).attr("y",g+r.y).text("Week "+(y+1)).attr("font-size",r.size).attr("fill","black").attr("pointer-events","none");b.label=a;b.placeLabel=c(l,d,g,k);b.moneyLabel=c(l,d,g,F);b.winsLabel=c(l,d,g,D);b.pointsLabel=c(l,d,g,t);b.elimsLabel=c(l,d,g,E);m.push(b);
y++});var x=l.append("rect").attr("x",0).attr("y",0).attr("width",135).attr("height",87).attr("fill","none").attr("stroke","black").attr("stroke-width",0).attr("pointer-events","none").attr("rx",cornerRadius).attr("ry",cornerRadius);var z=function(a){var d=a.attr("data");if(q.filter(function(a){return a.num==d})[0].done){var c="Week "+d;clearPlayer(null);if(""===filters.week)filters.week=c,p.filter(filters.week),a.transition().duration(100).attr("stroke-width",11),p.redrawGroup(),updateCounts(),n=
a,b(!0);else if(filters.week!=c){var g=filters.week;m.forEach(function(a){a=d3.select(a.rect._groups[0][0]);"Week "+a.attr("data")==g&&(p.filter(g),a.transition().duration(100).attr("stroke-width",0))});filters.week=c;p.filter(filters.week);a.transition().duration(100).attr("stroke-width",0);p.redrawGroup();updateCounts();n=a;b(!1)}else filters.week="",p.filter(null),a.transition().duration(100).attr("stroke-width",0),p.redrawGroup(),n=a,b(!0),updateCounts()}};showPlayerOnWeekChart=function(a){var b=
""===a,d=facts.all().filter(function(b){return b.player===a}),c=0;q.forEach(function(a){var g=d3.format(",d"),e=d.filter(function(b){return a.name===b.week}),f=0!=e.length&&!b,h=f?C:r,k=f?"1.0":"0.0",l=0!=e.length&&0<e[0].soloQual+e[0].duoQual;w[c].transition().style("fill-opacity",l?1:0);var u=l="",q="",p="",n="";f&&(l="# "+e[0].rank,u="$ "+g(e[0].payout),q=e[0].wins.toString()+(1===q?" win":" wins"),p=e[0].points+" points",n=e[0].elims.toString()+(1===n?" elim":" elims"));g="Solo"===a.type?10:155;
e=97*Math.round((c-1)/2)+40;m[c].label.transition().attr("x",g+h.x).attr("y",e+h.y).attr("font-size",h.size);m[c].placeLabel.text(l).transition().attr("fill-opacity",k);m[c].moneyLabel.text(u).transition().attr("fill-opacity",k);m[c].winsLabel.text(q).transition().attr("fill-opacity",k);m[c].pointsLabel.text(p).transition().attr("fill-opacity",k);m[c].elimsLabel.text(n).transition().attr("fill-opacity",k);c++});updateCounts()};return p};var playerDim,playerStatsGroup,LeftSideWidth=340,PlayerTableWidth=960,playerColors,theWeekChart,facts,selectedPlayerNode,showPlayerOnWeekChart,clearPlayer,soloQualifications=[],duoQualifications=[],cornerRadius=8,green="#319236",purple="#9D4DBB",blue="#4C51F7",red="#DB4441",teal="#3E93BC",lime="#3CFF3E",grey="#B3B3B3",brown="#8B4513",filters={week:"",region:"",search:"",player:"",sort:"payout",page:0,playerCount:0};
d3.json("fwc/data/data.json").then(function(a){var b=LeftSideWidth+PlayerTableWidth-20,c=title(b);disclaimer(c);a.forEach(function(a){a.rank=+a.rank;a.payout=+a.payout;a.points=+a.points});makeQualifications(a);facts=crossfilter(a);draw(facts);helpButton(c,b);d3.select("#search-input").on("keyup",function(a){filters.player="";showPlayerOnWeekChart();var b=document.getElementById("search-input").value;filters.search=b;playerDim.filter(function(a){return-1!==a.toLowerCase().indexOf(b.toLowerCase())});
updateCounts();dc.redrawAll()})});function makeQualifications(a){a.forEach(function(a){0!=a.soloQual&&soloQualifications.push(a.player);0!=a.duoQual&&duoQualifications.push(a.player)})}function title(a){a=d3.select(".title").append("svg").attr("width",a+"px").attr("height","70px");a.append("text").attr("x",0).attr("y",65).text("FORTNITE  World Cup Stats").attr("font-size","1.1em").attr("fill","black");return a}
function disclaimer(a){a.append("text").attr("x",866).attr("y",53).text("Includes top 100 in each region for each week").attr("font-size","1.3rem").attr("fill","black").attr("font-weight",400)}
function helpButton(a,b){a.append("circle").attr("cx",b-30).attr("cy",46).attr("r",22).attr("fill","green").attr("stroke","black").attr("stroke-width",0).on("mouseover",function(a){d3.select(this).transition().duration(50).attr("stroke-width",4)}).on("mouseout",function(a){d3.select(this).transition().duration(50).attr("stroke-width",0)}).on("click",function(a){window.open("help.html","_blank")});a.append("text").attr("x",b-38).attr("y",61).text("?").attr("font-size",".7em").attr("fill","black").attr("pointer-events",
"none")}
function updateCounts(){makePlayerStatsGroup(playerDim);if(""!=filters.player)var a=filters.player;else{a=[];""!=filters.region&&a.push(filters.region);""!=filters.week&&a.push(filters.week);""!=filters.search&&a.push('"'+filters.search+'"');var b=d3.format(",d");a.push(b(filters.playerCount)+" players");a=a.join(" / ");b=filters.sort.charAt(0).toUpperCase()+filters.sort.slice(1);switch(filters.sort){case "earnedQualifications":b="Earned Quals";break;case "elims":b="Elim Points";break;case "elimPercentage":b="Elim %";
break;case "placementPoints":b="Placement Points";break;case "placementPercentage":b="Placement %"}a+=" by "+b}d3.select("#count-box").text(" "+a)}
function draw(a){playerDim=a.dimension(dc.pluck("player"));makePlayerColors();makePlayerStatsGroup(playerDim);var b=a.dimension(dc.pluck("region")),c=b.group().reduceSum(dc.pluck("payout"));a=a.dimension(dc.pluck("week"));var u=a.group().reduceSum(dc.pluck("payout"));weekChart("#chart-weeks").dimension(a).group(u);regionChart("#chart-region").dimension(b).group(c);b=playerChart("#chart-player").dimension(playerStatsGroup);dc.registerChart(b,null);dc.renderAll();updateCounts()}
function makePlayerColors(){playerColors={};playerDim.top(Infinity).forEach(function(a){playerColors[a.player]=getColorForRegion(a.region)})}function getColorForRegion(a){switch(a){case "NA West":return"purple";case "NA East":return"green";case "Europe":return"blue";case "Oceana":return"red";case "Asia":return"brown";case "Brazil":return"teal"}}
function makePlayerStatsGroup(){playerStatsGroup=playerDim.group().reduce(function(a,b){a.soloQual+=b.soloQual;a.duoQual+=b.duoQual;a.rank+=b.rank;a.payout+=b.payout;a.points+=b.points;a.wins+=b.wins;a.elims+=b.elims;a.elimPercentage=a.elims/a.points;a.placementPoints+=b.placementPoints;a.placementPercentage=a.placementPoints/a.points;a.earnedQualifications+=b.earnedQualifications;return a},function(a,b){a.soloQual-=b.soloQual;a.duoQual-=b.duoQual;a.rank-=b.rank;a.payout-=b.payout;a.points-=b.points;
a.wins-=b.wins;a.elims-=b.elims;a.elimPercentage=a.elims/a.points;a.placementPoints-=b.placementPoints;a.placementPercentage=a.placementPoints/a.points;a.earnedQualifications-=b.earnedQualifications;return a},function(a){return{soloQual:0,duoQual:0,rank:0,payout:0,points:0,wins:0,elims:0,elimPercentage:0,placementPoints:0,placementPercentage:0,earnedQualifications:0}})};