
SELECT * FROM Names

SELECT * FROM Player



SELECT 'UPDATE Player SET Name = ''' + [Epic Name] + ''' WHERE CsvName = ''' + Name + ''''
FROM Names WHERE [Epic Name] <> ''


UPDATE Player SET Name = 'TOP_Banny Iwnl' WHERE CsvName = 'Banny'
UPDATE Player SET Name = 'Can''t type it. ' WHERE CsvName = 'FaxFox'
UPDATE Player SET Name = 'TriggerQQ Flame' WHERE CsvName = 'Flame'
UPDATE Player SET Name = 'Code Meta-Hood.J' WHERE CsvName = 'Hood.J'
UPDATE Player SET Name = 'Meta Peterpan' WHERE CsvName = 'Peterpan'
UPDATE Player SET Name = 'Scarlët' WHERE CsvName = 'Scarlet'
UPDATE Player SET Name = 'Cant spell' WHERE CsvName = 'Takamura'
UPDATE Player SET Name = 'TriggerQQ Uniq' WHERE CsvName = 'Uniq'
UPDATE Player SET Name = 'Newbee_xMende' WHERE CsvName = 'Xmende'
UPDATE Player SET Name = 'NewbeeXXM' WHERE CsvName = 'XXM'
UPDATE Player SET Name = 'dk iwnl' WHERE CsvName = 'drakoNz'
UPDATE Player SET Name = '9z King' WHERE CsvName = 'k1ng'
UPDATE Player SET Name = 'Kurtz' WHERE CsvName = 'kurtz'
UPDATE Player SET Name = 'Lasers is bad' WHERE CsvName = 'Lasers'
UPDATE Player SET Name = 'Code Leleo' WHERE CsvName = 'Leleo'
UPDATE Player SET Name = 'CODE NICKSSS' WHERE CsvName = 'NICKS'
UPDATE Player SET Name = 'xown iwnl-' WHERE CsvName = 'xOwN'
UPDATE Player SET Name = 'BTL 4zr' WHERE CsvName = '4zr'
UPDATE Player SET Name = 'VP 7ssk7' WHERE CsvName = '7ssk7'
UPDATE Player SET Name = 'Solary Airwaks' WHERE CsvName = 'Airwaks'
UPDATE Player SET Name = 'COOLER Aqua' WHERE CsvName = 'Aqua'
UPDATE Player SET Name = 'ÃRG' WHERE CsvName = 'ÃRG'
UPDATE Player SET Name = 'NotBadSniper' WHERE CsvName = 'BadSniper'
UPDATE Player SET Name = 'hREDS BELAEU' WHERE CsvName = 'BELAEU'
UPDATE Player SET Name = 'NRG Benjyfishy' WHERE CsvName = 'Benjyfishy'
UPDATE Player SET Name = 'TrainH BlastRR' WHERE CsvName = 'BlastR'
UPDATE Player SET Name = 'LeStream Blaxou' WHERE CsvName = 'Blaxou'
UPDATE Player SET Name = 'VHV Chapix' WHERE CsvName = 'Chapix'
UPDATE Player SET Name = 'TTVCoreGamingg' WHERE CsvName = 'CoreGamingg'
UPDATE Player SET Name = 'VHV Crue' WHERE CsvName = 'Crue'
UPDATE Player SET Name = 'Derox. ' WHERE CsvName = 'Derox'
UPDATE Player SET Name = 'Diego uwu' WHERE CsvName = 'DiegoGB'
UPDATE Player SET Name = 'Secret_Domentos' WHERE CsvName = 'Domentos'
UPDATE Player SET Name = 'Emqu' WHERE CsvName = 'Emqu'
UPDATE Player SET Name = 'Gambit.fwexY' WHERE CsvName = 'fwexY'
UPDATE Player SET Name = 'Solary Hunter' WHERE CsvName = 'Hunter'
UPDATE Player SET Name = 'Ghost' WHERE CsvName = 'Issa'
UPDATE Player SET Name = 'E11 Itemm' WHERE CsvName = 'itemm'
UPDATE Player SET Name = 'VP JAMSIDE' WHERE CsvName = 'Jamside'
UPDATE Player SET Name = 'Atlantis K1nzell' WHERE CsvName = 'K1nzell'
UPDATE Player SET Name = 'Solary Kinstaar' WHERE CsvName = 'Kinstaar'
UPDATE Player SET Name = 'RBK LeftEye' WHERE CsvName = 'LeftEye'
UPDATE Player SET Name = 'Gambit.letw1k3' WHERE CsvName = 'letw1k3'
UPDATE Player SET Name = 'LuKi tjk' WHERE CsvName = 'Luki'
UPDATE Player SET Name = 'HORT_LYGTH' WHERE CsvName = 'Lygth'
UPDATE Player SET Name = 'Lootboy Mexe' WHERE CsvName = 'Mexe'
UPDATE Player SET Name = 'Mitr0' WHERE CsvName = 'Mitr0'
UPDATE Player SET Name = 'Secret_Mongraal' WHERE CsvName = 'Mongraal'
UPDATE Player SET Name = 'NRG MrSavageM' WHERE CsvName = 'MrSavageM'
UPDATE Player SET Name = 'LeStream Nayte' WHERE CsvName = 'Nayte'
UPDATE Player SET Name = 'Solary Nikof' WHERE CsvName = 'Nikof'
UPDATE Player SET Name = 'Norward.' WHERE CsvName = 'Noward'
UPDATE Player SET Name = 'COOLER Nyhrox' WHERE CsvName = 'Nyhrox'
UPDATE Player SET Name = 'Oslo.' WHERE CsvName = 'Oslo'
UPDATE Player SET Name = 'TQ Prisi0n3r0' WHERE CsvName = 'Prisi0n3r0'
UPDATE Player SET Name = 'Eon RedRush' WHERE CsvName = 'RedRush'
UPDATE Player SET Name = 'TrainH Robabz' WHERE CsvName = 'Robabz'
UPDATE Player SET Name = 'Rojo' WHERE CsvName = 'Rojo'
UPDATE Player SET Name = 'Skailereu' WHERE CsvName = 'Skailereu'
UPDATE Player SET Name = 'Lootboy Skram' WHERE CsvName = 'Skram'
UPDATE Player SET Name = 'Fnatic Smeef' WHERE CsvName = 'Smeef'
UPDATE Player SET Name = 'E11 Stompy' WHERE CsvName = 'Stompy'
UPDATE Player SET Name = 'Tchub_' WHERE CsvName = 'Tchub'
UPDATE Player SET Name = 'dMind.Teeq' WHERE CsvName = 'Teeq'
UPDATE Player SET Name = 'E11 Tschiiinken' WHERE CsvName = 'Tschinken'
UPDATE Player SET Name = 'Atlantis Tuckz' WHERE CsvName = 'Tuckz'
UPDATE Player SET Name = 'LeStream Vato' WHERE CsvName = 'Vato'
UPDATE Player SET Name = 'FaZe Vorwenn' WHERE CsvName = 'Vorwenn'
UPDATE Player SET Name = 'Eon Wakie' WHERE CsvName = 'Wakie'
UPDATE Player SET Name = 'Eon Znappy' WHERE CsvName = 'Znappy'
UPDATE Player SET Name = 'CODE Sen-Aspect' WHERE CsvName = 'Aspect'
UPDATE Player SET Name = 'Astonish' WHERE CsvName = 'Astonish'
UPDATE Player SET Name = 'Ghost Bizzle' WHERE CsvName = 'Bizzle'
UPDATE Player SET Name = 'E11 BlooTea' WHERE CsvName = 'BlooTea'
UPDATE Player SET Name = 'Envy Bucke' WHERE CsvName = 'Bucke'
UPDATE Player SET Name = 'SEN Bugha' WHERE CsvName = 'Bugha'
UPDATE Player SET Name = 'Calculator' WHERE CsvName = 'Calculator'
UPDATE Player SET Name = '100T Ceice' WHERE CsvName = 'Ceice'
UPDATE Player SET Name = 'Chenkinz' WHERE CsvName = 'Chenkinz'
UPDATE Player SET Name = 'RS ClarityG' WHERE CsvName = 'ClarityG'
UPDATE Player SET Name = 'MSF Clix' WHERE CsvName = 'Clix'
UPDATE Player SET Name = 'TSM_Comadon' WHERE CsvName = 'Comadon'
UPDATE Player SET Name = 'FaZe Dubs.' WHERE CsvName = 'Dubs'
UPDATE Player SET Name = '100T Elevate' WHERE CsvName = 'Elevate'
UPDATE Player SET Name = 'KNG Fatch.' WHERE CsvName = 'Fatch'
UPDATE Player SET Name = 'FaZCe Funk' WHERE CsvName = 'FunkBomb'
UPDATE Player SET Name = 'KeysFN' WHERE CsvName = 'Keys'
UPDATE Player SET Name = '100T Klass' WHERE CsvName = 'Klass'
UPDATE Player SET Name = 'RS Kolorful' WHERE CsvName = 'kolorfull'
UPDATE Player SET Name = 'LZR Kreo' WHERE CsvName = 'Kreo'
UPDATE Player SET Name = 'coL Lanjok' WHERE CsvName = 'Lanjok'
UPDATE Player SET Name = 'Envy LeNain' WHERE CsvName = 'LeNain'
UPDATE Player SET Name = 'Thiccboy Lunze' WHERE CsvName = 'Luneze'
UPDATE Player SET Name = 'coL Mackwood' WHERE CsvName = 'MackWood'
UPDATE Player SET Name = 'FaZe Megga.' WHERE CsvName = 'Megga'
UPDATE Player SET Name = 'CLG Psalm' WHERE CsvName = 'Psalm'
UPDATE Player SET Name = 'coL Punisher' WHERE CsvName = 'Punisher'
UPDATE Player SET Name = 'RogueShark_' WHERE CsvName = 'RogueShark'
UPDATE Player SET Name = 'Code Ronaldo' WHERE CsvName = 'Ronaldo'
UPDATE Player SET Name = 'KNG Unknown' WHERE CsvName = 'Unknown'
UPDATE Player SET Name = 'TSM_Vinny1x' WHERE CsvName = 'Vinny1x'
UPDATE Player SET Name = 'Liquid Vivid' WHERE CsvName = 'Vivid'
UPDATE Player SET Name = 'NRG Zayt' WHERE CsvName = 'Zayt'
UPDATE Player SET Name = 'TSM_Zexrow' WHERE CsvName = 'Zexrow'
UPDATE Player SET Name = '4DRStorm.' WHERE CsvName = '4DRStorm'
UPDATE Player SET Name = 'Arkhram1x' WHERE CsvName = 'Arkhram'
UPDATE Player SET Name = 'Ghost Aydan' WHERE CsvName = 'Aydan'
UPDATE Player SET Name = 'KNG Jay.' WHERE CsvName = 'Jay'
UPDATE Player SET Name = 'Karhu' WHERE CsvName = 'karhu'
UPDATE Player SET Name = 'KNG Little' WHERE CsvName = 'little'
UPDATE Player SET Name = '1400 Pika' WHERE CsvName = 'Pika'
UPDATE Player SET Name = 'USE CODE Pzuhs' WHERE CsvName = 'Pzuhs'
UPDATE Player SET Name = '1400 Rhux uwu' WHERE CsvName = 'Rhux'
UPDATE Player SET Name = 'Liquid Riversan' WHERE CsvName = 'Riversan'
UPDATE Player SET Name = 'Ghost Sean' WHERE CsvName = 'Sean'
UPDATE Player SET Name = 'Snow xd' WHERE CsvName = 'snow'
UPDATE Player SET Name = 'Can not spell' WHERE CsvName = 'Cat'
UPDATE Player SET Name = 'Link' WHERE CsvName = 'Link'
UPDATE Player SET Name = 'Parpy' WHERE CsvName = 'Parpy'
UPDATE Player SET Name = 'Slaya' WHERE CsvName = 'slaya'
UPDATE Player SET Name = 'cant spell it' WHERE CsvName = 'sozmann'
UPDATE Player SET Name = 'Code Twizz' WHERE CsvName = 'Twizz'
UPDATE Player SET Name = 'Volx' WHERE CsvName = 'volx'
UPDATE Player SET Name = 'Twins iwnl' WHERE CsvName = 'x2twins Jordan'




SELECT 'UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = ''' + [Epic Name] + ''') WHERE Player = ''' + [Epic Name] + '''' 
FROM Names WHERE [Epic Name] <> ''



UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'TOP_Banny Iwnl') WHERE Player = 'TOP_Banny Iwnl'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'Can''t type it. ') WHERE Player = 'Can''t type it. '
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'TriggerQQ Flame') WHERE Player = 'TriggerQQ Flame'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'Code Meta-Hood.J') WHERE Player = 'Code Meta-Hood.J'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'Meta Peterpan') WHERE Player = 'Meta Peterpan'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'Scarlët') WHERE Player = 'Scarlët'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'Cant spell') WHERE Player = 'Cant spell'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'TriggerQQ Uniq') WHERE Player = 'TriggerQQ Uniq'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'Newbee_xMende') WHERE Player = 'Newbee_xMende'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'NewbeeXXM') WHERE Player = 'NewbeeXXM'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'dk iwnl') WHERE Player = 'dk iwnl'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = '9z King') WHERE Player = '9z King'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'Kurtz') WHERE Player = 'Kurtz'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'Lasers is bad') WHERE Player = 'Lasers is bad'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'Code Leleo') WHERE Player = 'Code Leleo'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'CODE NICKSSS') WHERE Player = 'CODE NICKSSS'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'xown iwnl-') WHERE Player = 'xown iwnl-'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'BTL 4zr') WHERE Player = 'BTL 4zr'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'VP 7ssk7') WHERE Player = 'VP 7ssk7'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'Solary Airwaks') WHERE Player = 'Solary Airwaks'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'COOLER Aqua') WHERE Player = 'COOLER Aqua'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'ÃRG') WHERE Player = 'ÃRG'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'NotBadSniper') WHERE Player = 'NotBadSniper'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'hREDS BELAEU') WHERE Player = 'hREDS BELAEU'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'NRG Benjyfishy') WHERE Player = 'NRG Benjyfishy'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'TrainH BlastRR') WHERE Player = 'TrainH BlastRR'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'LeStream Blaxou') WHERE Player = 'LeStream Blaxou'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'VHV Chapix') WHERE Player = 'VHV Chapix'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'TTVCoreGamingg') WHERE Player = 'TTVCoreGamingg'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'VHV Crue') WHERE Player = 'VHV Crue'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'Derox. ') WHERE Player = 'Derox. '
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'Diego uwu') WHERE Player = 'Diego uwu'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'Secret_Domentos') WHERE Player = 'Secret_Domentos'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'Emqu') WHERE Player = 'Emqu'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'Gambit.fwexY') WHERE Player = 'Gambit.fwexY'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'Solary Hunter') WHERE Player = 'Solary Hunter'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'Ghost') WHERE Player = 'Ghost'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'E11 Itemm') WHERE Player = 'E11 Itemm'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'VP JAMSIDE') WHERE Player = 'VP JAMSIDE'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'Atlantis K1nzell') WHERE Player = 'Atlantis K1nzell'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'Solary Kinstaar') WHERE Player = 'Solary Kinstaar'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'RBK LeftEye') WHERE Player = 'RBK LeftEye'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'Gambit.letw1k3') WHERE Player = 'Gambit.letw1k3'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'LuKi tjk') WHERE Player = 'LuKi tjk'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'HORT_LYGTH') WHERE Player = 'HORT_LYGTH'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'Lootboy Mexe') WHERE Player = 'Lootboy Mexe'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'Mitr0') WHERE Player = 'Mitr0'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'Secret_Mongraal') WHERE Player = 'Secret_Mongraal'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'NRG MrSavageM') WHERE Player = 'NRG MrSavageM'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'LeStream Nayte') WHERE Player = 'LeStream Nayte'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'Solary Nikof') WHERE Player = 'Solary Nikof'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'Norward.') WHERE Player = 'Norward.'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'COOLER Nyhrox') WHERE Player = 'COOLER Nyhrox'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'Oslo.') WHERE Player = 'Oslo.'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'TQ Prisi0n3r0') WHERE Player = 'TQ Prisi0n3r0'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'Eon RedRush') WHERE Player = 'Eon RedRush'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'TrainH Robabz') WHERE Player = 'TrainH Robabz'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'Rojo') WHERE Player = 'Rojo'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'Skailereu') WHERE Player = 'Skailereu'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'Lootboy Skram') WHERE Player = 'Lootboy Skram'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'Fnatic Smeef') WHERE Player = 'Fnatic Smeef'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'E11 Stompy') WHERE Player = 'E11 Stompy'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'Tchub_') WHERE Player = 'Tchub_'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'dMind.Teeq') WHERE Player = 'dMind.Teeq'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'E11 Tschiiinken') WHERE Player = 'E11 Tschiiinken'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'Atlantis Tuckz') WHERE Player = 'Atlantis Tuckz'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'LeStream Vato') WHERE Player = 'LeStream Vato'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'FaZe Vorwenn') WHERE Player = 'FaZe Vorwenn'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'Eon Wakie') WHERE Player = 'Eon Wakie'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'Eon Znappy') WHERE Player = 'Eon Znappy'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'CODE Sen-Aspect') WHERE Player = 'CODE Sen-Aspect'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'Astonish') WHERE Player = 'Astonish'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'Ghost Bizzle') WHERE Player = 'Ghost Bizzle'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'E11 BlooTea') WHERE Player = 'E11 BlooTea'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'Envy Bucke') WHERE Player = 'Envy Bucke'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'SEN Bugha') WHERE Player = 'SEN Bugha'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'Calculator') WHERE Player = 'Calculator'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = '100T Ceice') WHERE Player = '100T Ceice'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'Chenkinz') WHERE Player = 'Chenkinz'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'RS ClarityG') WHERE Player = 'RS ClarityG'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'MSF Clix') WHERE Player = 'MSF Clix'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'TSM_Comadon') WHERE Player = 'TSM_Comadon'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'FaZe Dubs.') WHERE Player = 'FaZe Dubs.'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = '100T Elevate') WHERE Player = '100T Elevate'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'KNG Fatch.') WHERE Player = 'KNG Fatch.'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'FaZCe Funk') WHERE Player = 'FaZCe Funk'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'KeysFN') WHERE Player = 'KeysFN'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = '100T Klass') WHERE Player = '100T Klass'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'RS Kolorful') WHERE Player = 'RS Kolorful'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'LZR Kreo') WHERE Player = 'LZR Kreo'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'coL Lanjok') WHERE Player = 'coL Lanjok'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'Envy LeNain') WHERE Player = 'Envy LeNain'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'Thiccboy Lunze') WHERE Player = 'Thiccboy Lunze'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'coL Mackwood') WHERE Player = 'coL Mackwood'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'FaZe Megga.') WHERE Player = 'FaZe Megga.'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'CLG Psalm') WHERE Player = 'CLG Psalm'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'coL Punisher') WHERE Player = 'coL Punisher'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'RogueShark_') WHERE Player = 'RogueShark_'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'Code Ronaldo') WHERE Player = 'Code Ronaldo'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'KNG Unknown') WHERE Player = 'KNG Unknown'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'TSM_Vinny1x') WHERE Player = 'TSM_Vinny1x'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'Liquid Vivid') WHERE Player = 'Liquid Vivid'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'NRG Zayt') WHERE Player = 'NRG Zayt'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'TSM_Zexrow') WHERE Player = 'TSM_Zexrow'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = '4DRStorm.') WHERE Player = '4DRStorm.'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'Arkhram1x') WHERE Player = 'Arkhram1x'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'Ghost Aydan') WHERE Player = 'Ghost Aydan'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'KNG Jay.') WHERE Player = 'KNG Jay.'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'Karhu') WHERE Player = 'Karhu'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'KNG Little') WHERE Player = 'KNG Little'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = '1400 Pika') WHERE Player = '1400 Pika'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'USE CODE Pzuhs') WHERE Player = 'USE CODE Pzuhs'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = '1400 Rhux uwu') WHERE Player = '1400 Rhux uwu'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'Liquid Riversan') WHERE Player = 'Liquid Riversan'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'Ghost Sean') WHERE Player = 'Ghost Sean'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'Snow xd') WHERE Player = 'Snow xd'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'Can not spell') WHERE Player = 'Can not spell'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'Link') WHERE Player = 'Link'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'Parpy') WHERE Player = 'Parpy'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'Slaya') WHERE Player = 'Slaya'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'cant spell') WHERE Player = 'cant spell'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'Code Twizz') WHERE Player = 'Code Twizz'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'Volx') WHERE Player = 'Volx'
UPDATE Placement SET PlayerID = (SELECT ID FROM Player WHERE Name = 'Twins iwnl') WHERE Player = 'Twins iwnl'
